security:
  oauth2:
    client:
      clientId: 809417833574-8tumv1us497f24hd12fi2anr1ug7bp6c.apps.googleusercontent.com
      clientSecret: RK3FQTQY0fHu1dG8cCJuP_jo
      accessTokenUri: https://www.googleapis.com/oauth2/v3/tokeninfo
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false
